#!/usr/bin/env python3
"""Embed bundled TurboQuant codebook JSONs into a C++ translation unit.

Output file exports:
    namespace tq {
        std::span<const CodebookBlob> embedded_codebooks() noexcept;
    }

Each CodebookBlob points at `static constexpr float` arrays with the
centroids and *interior* decision boundaries (boundaries[1:-1], matching
quantizer.py:127 — the slice that searchsorted operates on).

Usage:
    codebooks_to_cpp.py --in <codebook_dir> --out <generated_cpp>
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import re
import sys
from typing import List, Tuple


CODEBOOK_RE = re.compile(r"codebook_d(\d+)_b(\d+)\.json$")


def load_codebook(path: str) -> dict:
    with open(path, "r") as f:
        data = json.load(f)
    for key in ("centroids", "boundaries", "d", "bits", "mse_per_coord", "mse_total"):
        if key not in data:
            raise ValueError(f"{path}: missing key '{key}'")
    d = int(data["d"])
    bits = int(data["bits"])
    n_clusters = 2 ** bits
    if len(data["centroids"]) != n_clusters:
        raise ValueError(f"{path}: expected {n_clusters} centroids, got {len(data['centroids'])}")
    if len(data["boundaries"]) != n_clusters + 1:
        raise ValueError(f"{path}: expected {n_clusters + 1} boundaries, got {len(data['boundaries'])}")
    # Validate bounds
    if data["boundaries"][0] != -1.0 or data["boundaries"][-1] != 1.0:
        raise ValueError(f"{path}: boundaries must start with -1.0 and end with 1.0")
    # Monotonicity
    centroids = data["centroids"]
    for i in range(len(centroids) - 1):
        if centroids[i] >= centroids[i + 1]:
            raise ValueError(f"{path}: centroids not strictly increasing at index {i}")
    return data


def float_literal(x: float) -> str:
    # Emit with enough precision for round-trip; append 'f' for float.
    # repr() gives shortest-round-trip decimal in Python 3.1+.
    s = repr(x)
    if "e" in s or "E" in s:
        return s + "f"
    if "." not in s and "nan" not in s and "inf" not in s:
        s += ".0"
    return s + "f"


def emit(in_dir: str, out_path: str) -> int:
    jsons: List[Tuple[int, int, str]] = []
    for path in sorted(glob.glob(os.path.join(in_dir, "codebook_d*_b*.json"))):
        m = CODEBOOK_RE.search(os.path.basename(path))
        if not m:
            continue
        d = int(m.group(1))
        bits = int(m.group(2))
        jsons.append((d, bits, path))
    jsons.sort()

    lines: List[str] = []
    lines.append("// GENERATED by tools/codebooks_to_cpp.py — do not edit.")
    lines.append("")
    lines.append('#include "turboquant/codebook.hpp"')
    lines.append("")
    lines.append("#include <cstddef>")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("namespace tq {")
    lines.append("namespace {")
    lines.append("")

    for d, bits, path in jsons:
        cb = load_codebook(path)
        centroids = cb["centroids"]
        boundaries = cb["boundaries"]
        interior = boundaries[1:-1]

        lines.append(f"// d={d}, bits={bits}   ({os.path.basename(path)})")
        lines.append(f"inline constexpr float kCentroids_d{d}_b{bits}[] = {{")
        for v in centroids:
            lines.append(f"    {float_literal(v)},")
        lines.append("};")
        lines.append("")
        lines.append(f"inline constexpr float kInteriorBoundaries_d{d}_b{bits}[] = {{")
        for v in interior:
            lines.append(f"    {float_literal(v)},")
        lines.append("};")
        lines.append("")

    lines.append("inline constexpr CodebookBlob kBlobs[] = {")
    for d, bits, path in jsons:
        cb = load_codebook(path)
        mse_pc = float_literal(cb["mse_per_coord"])
        mse_tot = float_literal(cb["mse_total"])
        lines.append(
            f"    {{ {d}u, {bits}u, {mse_pc}, {mse_tot}, "
            f"kCentroids_d{d}_b{bits}, kInteriorBoundaries_d{d}_b{bits} }},"
        )
    lines.append("};")
    lines.append("")
    lines.append("} // namespace")
    lines.append("")
    lines.append("std::span<const CodebookBlob> embedded_codebooks() noexcept {")
    lines.append("    return { kBlobs, sizeof(kBlobs) / sizeof(kBlobs[0]) };")
    lines.append("}")
    lines.append("")
    lines.append("} // namespace tq")
    lines.append("")

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write("\n".join(lines))

    print(f"[codebooks_to_cpp] wrote {len(jsons)} blobs to {out_path}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="in_dir", required=True)
    ap.add_argument("--out", dest="out_path", required=True)
    args = ap.parse_args()
    if not os.path.isdir(args.in_dir):
        print(f"[codebooks_to_cpp] codebook dir missing: {args.in_dir}", file=sys.stderr)
        return 2
    return emit(args.in_dir, args.out_path)


if __name__ == "__main__":
    sys.exit(main())
